twitch:
  client_id: ''
  client_secret: ''
  username: ''
  channels:
    - ''
  ignored_users:
    - 'nightbot'
    - 'streamlabs'
  irc:
    server: 'irc.chat.twitch.tv'
    port: 6667
markov:
  generate_on: 35
  percent_unique: 50.0
  allow_mentions: True
  log_file: ''
  phrases_list: 
    - ''
  state_size: 2
  clear_logs_after: False
  send_messages: True
  times_to_try: 1000
  unique: True
  cull_over: 8000
  time_to_cull: 3600
  blacklist_file: ''