twitch:
  client_id: ''
  client_secret: ''
  username: ''
  channels:
    MiltonTPike1:
      ignored_users:
        - 'nightbot'
        - 'streamlabs'
      clear_logs_after: False
      send_messages: True
      unique: True
      generate_on: 35
  irc:
    server: 'irc.chat.twitch.tv'
    port: 6667
markov:
  percent_unique: 50.0
  allow_mentions: True
  state_size: 2
  times_to_try: 1000
  cull_over: 8000
  time_to_cull: 3600
  blacklist_file: ''
  defaults:
    ignored_users:
        - 'nightbot'
        - 'streamlabs'
    clear_logs_after: False
    send_messages: True
    unique: True
    generate_on: 35